/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kdserver;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author arathy
 */
public class UserRegister extends javax.swing.JFrame {

    /**
     * Creates new form UserRegister
     */
    public UserRegister() {
        initComponents();
        this.setBounds(100, 100, 700, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 110, 60, 14);

        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 160, 50, 14);

        jLabel4.setText("email Id");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 220, 50, 14);

        jLabel5.setText("Phone Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 290, 80, 14);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 370, 80, 23);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(350, 100, 80, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(350, 160, 80, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(350, 210, 80, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(350, 280, 80, 20);

        jButton2.setText("Login here");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 430, 220, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kdserver/images/Twitter-HD-Background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-90, -40, 800, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        String u = jTextField1.getText();
        String email = jTextField3.getText();
        String p=jTextField2.getText();
       // String cnp=cpwd.getText();
        String cphon=jTextField4.getText();
                boolean flag=true;
       if(u.length()==0)
       {
         JOptionPane.showMessageDialog(this,"please enter username");
         flag=false;
       }
       if(email.length()==0&& flag)
       {
         JOptionPane.showMessageDialog(this,"please enter mail id");
         flag=false;
       }
       if(p.length()==0&& flag)
       {
         JOptionPane.showMessageDialog(this,"please enter password");
         flag=false;
       }
      
     
       if(email.matches("[a-z,0-9]+@[a-z]+.[a-z]+") && flag)
       {
         flag=true;
       }
       else
       {
         JOptionPane.showMessageDialog(this,"not a valid mail id");
         flag=false;
       }
       if(cphon.matches("[0-9]+")&&flag)
       {
           flag=true;
       }
       else
       {
           JOptionPane.showMessageDialog(this,"not a valid mobile number");
       }
       if(flag)
       {

        try {
            String userName = "root";
            String password = "";
            String url = "jdbc:mysql://localhost/kbserver";
            //String url = "jdbc:mysql://localhost/sspais";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = DriverManager.getConnection(url, userName, password);
            Statement st = con.createStatement();
            String sql= "insert into user values('"+u+"','"+p+"','"+email+"','"+cphon+"')";
            st.executeUpdate(sql);
           
            UserLogin ul=new UserLogin();
            ul.setVisible(true);
             this.dispose();
            

          } catch (Exception ee) 
          {
            System.out.println(ee);
        }
       }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        UserLogin u=new UserLogin();
        u.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
